name: Build and Test Suite on Windows

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-tests:
    name: Test and Build
    strategy:
      matrix:
        platform:
          - windows-latest
        toolchain:
          - stable
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up MSVC environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Select CMake generator
        shell: bash
        run: |
          echo "CMAKE_GENERATOR=Visual Studio 17 2022" >> "$GITHUB_ENV"
          echo "CMAKE_GENERATOR_PLATFORM=x64" >> "$GITHUB_ENV"

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}

      - name: Build
        run: cargo build --locked --all --release --verbose
